describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://uberlandia.jmjsistemas.app/crm/#/authenticate')
    cy.get(':nth-child(1) > .login__input').type('laramos')
    cy.get('.ng-isolate-scope > #senha').type('kFOt6xfb7h')
    cy.get('.login__submit').click()
    cy.get('jmj-grupo-empresa.ng-isolate-scope > .row > .col-xs-12 > .ng-untouched > .form-control').type('seu_dominio')
    cy.get(':nth-child(3) > :nth-child(2) > .btn').click()
    cy.get(':nth-child(2) > .info-box > .info-box-content > .ng-binding').click()
    cy.get('.content-wrapper > :nth-child(1)')
    cy.get('.panel-body > :nth-child(2) > :nth-child(2) > .ng-untouched > .form-control').type('Duvida')
    cy.get('.panel-body > :nth-child(5) > :nth-child(2) > .btn').click()
    cy.get('.ui-grid-render-container-body > .ui-grid-viewport')
    cy.get('.breadcrumb > :nth-child(1) > .ng-binding').click()
    cy.get(':nth-child(3) > :nth-child(2) > .btn').click()
    cy.get(':nth-child(1) > .info-box > .info-box-content > h3 > :nth-child(1)').click()
    cy.get(':nth-child(3) > .info-box > .info-box-content > .ng-binding').click()
    cy.get(':nth-child(3) > .info-box > .info-box-icon')
    cy.get('.content-wrapper > :nth-child(1)')
  })
})